config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tweets#index', as: 'tweets_index'

  get '/tweet/new', to: 'tweets#new', as: 'new_tweet'

  get '/tweet/:id', to: 'tweets#show', as: 'show_tweet'

  get '/tweet/:id/update', to: 'tweets#update', as: 'update_tweet'

  get '/tweet/:id/delete', to: 'tweets#delete', as: 'delete_tweet'

  # post

  post '/post/tweet/new', to: 'tweets#post_new', as: 'post_new_tweet'

  post '/post/tweet/:id/update', to: 'tweets#post_update', as: 'post_update_tweet'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, allow_blank: false, allow_nil: false, length: {
    minimum: 1,
    maximum: 140,
    too_short: "%{count} characters is too short. Enter at least 1 character.",
    too_long: "%{count} characters is the maximum allowed"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @title = "List Of Tweets"
    @posts = Post.all
  end

  def new
    @title = "Create A New Tweet"
  end

  def show
    @id = params[:id]

    @post = Post.find(@id)
    @title = "Tweet : #{@post.id}"
  end

  def update
    @id = params[:id]

    @post = Post.find(@id)
    @title = "Update Tweet : #{@post.id}"
  end

  def delete
    @id = params[:id]

    @post = Post.find(@id)
    @tweet = @post.destroy()

    if @tweet
      flash[:success] = "deletion success"
      redirect_to tweets_index_path
    else
      flash[:danger] = "deletion failed"
      redirect_to show_tweet_path(id: @tweet.id)
    end
  end

  # --- post methods

  def post_new
    @content = params[:content]
    if @content.nil? || @content.length < 1 || @content.length > 140
      flash[:danger] = "tweet content is invalid"
      redirect_to new_tweet_path
    else
      @tweet = Post.create(content: @content)

      if @tweet.valid?
        flash[:success] = "create success"
        redirect_to show_tweet_path(id: @tweet.id)
      else
        flash[:danger] = "create failed"
        redirect_to show_tweet_path(id: @tweet.id)
      end
    end
  end

  def post_update
    @id = params[:id]
    @content = params[:content]

    if @content.nil? || @content.length < 1 || @content.length > 140
      flash[:danger] = "tweet content is invalid"
      redirect_to new_tweet_path
    else
      @post = Post.find(@id)
      @tweet = @post.update(content: @content)

      if @tweet
        flash[:success] = "update success"
        redirect_to show_tweet_path(id: @post.id)
      else
        flash[:danger] = "update failed"
        redirect_to show_tweet_path(id: @post.id)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>DiveIntoCode &mdash; Application Tweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1><%= @title %></h1>
      <nav>
        <ul>
          <li><a id="all" href="<%= tweets_index_path  %>">ALL</a></li>
          <li><a id="new" href="<%= new_tweet_path %>">NEW</a></li>
        </ul>
      </nav>
    </header>

    <main>

      <% flash.each do |type, msg| %>
        <div class="alert <%= type %>">
          <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <footer>
      <p>Copyright &copy; ludndev</p>
    </footer>
    <script>
        var close = document.getElementsByClassName("closebtn");
        var i;

        for (i = 0; i < close.length; i++) {
            close[i].onclick = function(){
                var div = this.parentElement;
                div.style.opacity = "0";
                setTimeout(function(){ div.style.display = "none"; }, 600);
            }
        }
    </script>
  </body>
</html>

app/views/tweets/index.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Created At</th>
    <th>Content</th>
    <th>Action</th>
  </tr>

  <% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td title="<%= post.created_at %>"><%= time_ago_in_words(post.created_at) %></td>
    <td><%= post.content %></td>
    <td class="showBtn" >
      <a href="<%= show_tweet_path(id: post.id) %>">voir</a>
    </td>
  </tr>
  <% end %>
</table>

app/views/tweets/new.html.erb
<form action="<%= post_new_tweet_path %>" method="post" onsubmit="return validateMyForm();">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <label for="content">Content</label>
  <textarea name="content" id="content" cols="30" rows="10" minlength="1" maxlength="140" required></textarea>

  <button type="submit" name="submit">SAVE</button>
</form>

<script type="text/javascript" charset="utf-8">
    function validateMyForm() {
        if (confirm('Are you sure you want to post this tweet ?')) {
            window.localStorage.removeItem(lstag)
            return true;
        } else {
            return false;
        }
    }
</script>

app/views/tweets/show.html.erb
<table>
  <tr>
    <td><b>ID</b></td>
    <td><%= @post.id %></td>
  </tr>
  <tr>
    <td><b>Content</b></td>
    <td><%= @post.content %></td>
  </tr>
  <tr>
    <td><b>Created At</b></td>
    <td title="<%= @post.created_at %>"><%= time_ago_in_words(@post.created_at) %></td>
  </tr>
  <tr>
    <td><b>Last Update</b></td>
    <td title="<%= @post.updated_at %>"><%= time_ago_in_words(@post.updated_at) %></td>
  </tr>
</table>

<div class="flex-container">
  <div style="flex-grow: 3; background-color: dodgerblue;"><a href="<%= update_tweet_path(id: @post.id) %>">EDIT</a></div>
  <div style="flex-grow: 3; background-color: red;"><a href="#" onclick="check()">DELETE</a></div>
</div>

<script type="text/javascript" charset="utf-8">
  function check() {
      if (confirm('Are you sure you want to delete this tweet ?')) {
          window.location = "<%= delete_tweet_path(id: @post.id) %>";
      }
  }
</script>

app/views/tweets/update.html.erb
<form action="<%= post_update_tweet_path %>" method="post" onsubmit="return validateMyForm();">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <h2>Old Content</h2>
  <br>
  <p>
    <%= @post.content %>
  </p>

  <br><hr><br>

  <label for="content">Content</label>
  <textarea name="content" id="content" cols="30" rows="10" minlength="1" maxlength="140" required><%= @post.content %></textarea>

  <button type="submit" name="submit" onclick="window.localStorage.removeItem(lstag)">UPDATE</button>
</form>

<script>
    function validateMyForm() {
        return confirm('Are you sure you want to update this tweet ?');
    }
</script>